### ISSUE TITLE
"ghc --make site.hs" error,how to fix it?

### ISSUE THREAD

**Issue by luckypoem** [rosedu/techblog#32]
hi.

root@AR:/usr/local/rosedu-techblog# ghc --make site.hs
[1 of 1] Compiling Main             ( site.hs, site.o )

site.hs:257:67: error:
    • Couldn't match type ‘unordered-containers-0.2.7.1:Data.HashMap.Base.HashMap
                             Data.Text.Internal.Text
                             aeson-0.11.2.1:Data.Aeson.Types.Internal.Value’
                     with ‘M.Map [Char] String’
      Expected type: M.Map [Char] String
        Actual type: Metadata
    • In the second argument of ‘M.lookup’, namely ‘metadata’
      In the second argument of ‘($)’, namely
        ‘M.lookup "author" metadata’
      In the second argument of ‘($)’, namely
        ‘maybe [] (map trim . splitAll ",") $ M.lookup "author" metadata’
root@AR:/usr/local/rosedu-techblog#

thank you

**Comment by mihaimaruseac** [comment]
Hi. You need to use either `stack` or `cabal` to build the package.
